import "./globals.css";
import Navbar from "./components/navigation/Navbar";
import PageContainer from "./components/PageContainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased overflow-y-scroll"
      >
        <main className="min-h-screen bg-slate-50">
          <PageContainer>
            <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:gap-10">
              <Navbar />
              <div className="min-w-0 w-full flex-1">{children}</div>
            </div>
          </PageContainer>
        </main>
      </body>
    </html>
  );
}
